name: think_nest
description: "思巢-成长之光-安卓平板端."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #状态管理
  get: ^4.7.3
  #获取包信息
  package_info_plus: ^9.0.0
  # 本地存储
  shared_preferences: ^2.5.3
  # ui组件库
  ducafe_ui_core: ^1.0.6
  # 网络图片缓存
  cached_network_image: ^3.4.1
  # svg 图片  
  flutter_svg: ^2.2.3
  adaptive_theme: ^3.7.2
  #缓存
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0
  #桌面图标
  icons_launcher: ^3.0.3
  # 启动屏
  flutter_native_splash: ^2.4.7

# app 图标
icons_launcher:
  image_path: "assets/icons/icon.png"
  platforms:
    android:
      enable: true
      notification_image: "assets/icons/icon.png"
      # adaptive_background_color: '#ffffff'
      adaptive_background_image: "assets/icons/ic_background.png"
      adaptive_foreground_image: "assets/icons/icon.png"
    ios:
      enable: true

# 启动图适配 android 11 及以下, 12 以上，IOS
flutter_native_splash:
  web: false
  color_android: "#ffffff"
  #background_image_android: "assets/icons/logo.png"
  background_image_ios: "assets/icons/logo.png"
  # image_ios: "assets/launcher/android.png"
  android_12:
    image: "assets/icons/logo_small.png"
    # icon_background_color: "#324ea1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/courses/
    - assets/svgs/
    - assets/svgs/course/
    - assets/svgs/settings/
    - assets/svgs/integration/
    - assets/icons/

  fonts:
    - family: Alibaba-PuHuiTi
      fonts:
        - asset: assets/fonts/阿里巴巴普惠体-2-45-Light.otf
          weight: 300
        - asset: assets/fonts/阿里巴巴普惠体-2-55-Regular.otf
          weight: 400
        - asset: assets/fonts/阿里巴巴普惠体-2-65-Medium.otf
          weight: 500
        - asset: assets/fonts/阿里巴巴普惠体-2-85-Bold.otf
          weight: 700
